/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nurseryy;

import static java.awt.SystemColor.info;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SUDHARSHAN NAVADA K
 */
public class Place_Order extends javax.swing.JFrame {
   static String cid;
    static String pho;
    static String adrs;
    static String pidd;
   static String ssid;

    /**
     * Creates new form Place_Order
     */
    public Place_Order(String id,String ph,String addd,String pid,String sid) {
        
//        Place_Order()
//        {
//            
//        }
        cid=id;
        pho=ph;
        adrs=addd;
        pidd=pid;
        ssid=sid;
        initComponents();
        f2.setText(cid);
        f3.setText(pho);
        f4.setText(adrs);
        f5.setText(pidd);
        f9.setText(ssid);
        l1.setVisible(false);
        f8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pt1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tr8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        f8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        f4 = new javax.swing.JTextArea();
        f6 = new javax.swing.JTextField();
        f7 = new javax.swing.JTextField();
        fb = new javax.swing.JButton();
        f9 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1786, 931));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Oder_id          :");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 286, 160, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Cust_Id          :");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 359, 160, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Phone              :");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 432, 160, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Address           :");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 505, 160, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("Plant_id          :");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 686, 160, 40));

        f1.setBackground(new java.awt.Color(255, 255, 0));
        f1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        jPanel1.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 288, 250, 40));

        f2.setBackground(new java.awt.Color(255, 255, 0));
        f2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });
        jPanel1.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 361, 250, 40));

        f3.setBackground(new java.awt.Color(255, 255, 0));
        f3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });
        jPanel1.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 434, 250, 40));

        f5.setBackground(new java.awt.Color(255, 255, 0));
        f5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });
        jPanel1.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 686, 250, 40));

        pt1.setBackground(new java.awt.Color(255, 255, 0));
        pt1.setColumns(20);
        pt1.setRows(5);
        pt1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jScrollPane1.setViewportView(pt1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2754, 1107, 0));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel11.setText("                           GREEN HOUSE  NURSERY ");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 11, 1, new java.awt.Color(0, 20, 162)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 120));

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton4.setText("BACK");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.black, java.awt.Color.orange, java.awt.Color.black));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 1501, 170, 60));

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.black, java.awt.Color.orange, java.awt.Color.black));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 1501, 170, 60));

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton6.setText("ADD");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.black, java.awt.Color.orange, java.awt.Color.black));
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 1501, 170, 60));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Welcome to Order  page Please fill following contents about Order....");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, 780, 110));

        tr8.setBackground(new java.awt.Color(255, 255, 0));
        tr8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr8ActionPerformed(evt);
            }
        });
        jPanel1.add(tr8, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 1330, 250, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Department    :");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 1328, 160, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 873, 170, 60));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 873, 170, 60));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setText("CONFIRM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 873, 213, 60));

        l1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(51, 255, 255));
        l1.setText("Price               :");
        l1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 444, 160, 40));

        f8.setBackground(new java.awt.Color(255, 255, 0));
        f8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 444, 250, 40));

        f4.setBackground(new java.awt.Color(255, 255, 0));
        f4.setColumns(20);
        f4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f4.setRows(5);
        jScrollPane3.setViewportView(f4);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 505, 250, 146));

        f6.setBackground(new java.awt.Color(255, 255, 0));
        f6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f6ActionPerformed(evt);
            }
        });
        jPanel1.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 744, 250, 40));

        f7.setBackground(new java.awt.Color(255, 255, 0));
        f7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        f7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f7ActionPerformed(evt);
            }
        });
        jPanel1.add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 797, 250, 41));

        fb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fb.setText("GENERATE PRICE");
        fb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, java.awt.Color.yellow, java.awt.Color.red));
        fb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbActionPerformed(evt);
            }
        });
        jPanel1.add(fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 589, 257, 62));

        f9.setBackground(new java.awt.Color(255, 255, 0));
        f9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(f9, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 518, 250, 40));

        l2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(51, 255, 255));
        l2.setText("Salesman_id  :");
        l2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 518, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nurseryy/k5fit.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1100, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f1ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f2ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f3ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        f1.setText(null);
        f2.setText(null);
        f3.setText(null);
        f4.setText(null);
        f5.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tr8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Acust e=new Acust();
        e.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        f8.setText(null);
        f1.setText(null);
        f2.setText(null);
        f3.setText(null);
        f4.setText(null);
        f5.setText(null);
        f9.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection connection = null;
        PreparedStatement statement = null;

        String oid=f1.getText();
           String cid=f2.getText();
           int found=0;
        
        String ph=f3.getText();
        String ad=f4.getText();
        String p1=f5.getText();
        String p2=f6.getText();
        String p3=f7.getText();
        int pri=Integer.parseInt(f8.getText());
        String eid=f9.getText();
        
        

        // String pos=f6.getText();
        //int sal=Integer.parseInt(f6.getText());
        // String id=f2.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost:3308/nursery","root","");
           Statement s=connection.createStatement();
            String sql1="select * from custinfo";
            ResultSet r=s.executeQuery(sql1);
            while(r.next())
            {
                String sid=r.getString(2);
                if(cid.equals(sid))
                {
                    found=1;
                    break;
                }
            }
            if(found==1)
            {
            //File img=new File(pos);
            String sql="INSERT INTO `orderdatabase`(`Cust_id`, `Phone`, `Plant_id1`, `Plant_id2`, `Plant_id3`, `Order_id`, `Salesman_id`, `Price`, `Address`) VALUES ('"+cid+"','"+ph+"','"+p1+"','"+p2+"','"+p3+"','"+oid+"','"+eid+"','"+pri+"','"+ad+"')";
            statement = connection.prepareStatement(sql);
            
            
           

            statement.executeUpdate();
            /* ResultSet r;
            r = s.executeQuery("insert into custinfo(Name,Phone)"+"values('"+s1"','"+ph"')");*/
            JOptionPane.showMessageDialog(null, "ORDER PLACED SUCCESSFULLY....");
            f1.setText(null);
            f2.setText(null);
            f3.setText(null);
            f4.setText(null);
            f5.setText(null);
            f8.setText(null);
            f6.setText(null);
            f7.setText(null);
            f8.setText(null);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The customer id is invalid....");
            f1.setText(null);
            f2.setText(null);
            f3.setText(null);
            f4.setText(null);
            f5.setText(null);
            f8.setText(null);
            f6.setText(null);
            f7.setText(null);
            f8.setText(null);
            }

        }
        catch(Exception e){
            System.out.println(e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void f6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f6ActionPerformed

    private void f7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f7ActionPerformed

    private void fbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbActionPerformed
        
             int amount=0;
        f8.setVisible(true);
        l1.setVisible(true);
 try{ Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3308/nursery","root","");
            Statement st = c.createStatement();
            
            ResultSet r;
           
            
            r=st.executeQuery(" SELECT SUM(p.PriceP) FROM plantinfo p,orderdatabase o WHERE p.Plant_id IN(SELECT s.Plant_id FROM plantinfo s,orderdatabase o  WHERE s.Plant_id=o.Plant_id1 OR s.Plant_id=o.Plant_id2 OR s.Plant_id=o.Plant_id3);");
         amount=0;
         
            if(r.next())
                amount=r.getInt(1);
           // String a=Integer.toString(amount);
            System.out.println(amount);
            f8.setText(String.valueOf(amount));
            // create an input stream pointing to the image file to store
            // FileInputStream imageInputStream = new FileInputStream(img);
            // inform the statement that first parameter in the query is of binary type
            // statement.setBinaryStream(7, imageInputStream);
            // execute query

            // String sql="INSERT INTO `plantinfo`(`Name`, `Plant_id`, `Season`, `Count`, `Breed_no`, `ScientificName`, `More`) VALUES  ('"+name+"','"+id+"','"+sea+"','"+count1+"','"+breeds+"','"+sci+"','"+info+"')";
            //PreparedStatement ps = c.prepareStatement(sql);

           // statement.executeUpdate();
            /* ResultSet r;
            r = s.executeQuery("insert into custinfo(Name,Phone)"+"values('"+s1"','"+ph"')");*/
           

        }
        catch(Exception e){
            System.out.println(e);
        }// TODO add your handling code here// TODO add your handling code here:
    }//GEN-LAST:event_fbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Place_Order(cid,pho,adrs,pidd,ssid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextArea f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JTextField f7;
    private javax.swing.JTextField f8;
    private javax.swing.JTextField f9;
    private javax.swing.JButton fb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextArea pt1;
    private javax.swing.JTextField tr8;
    // End of variables declaration//GEN-END:variables
}
