/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nurseryy;

import static com.oracle.jrockit.jfr.ContentType.Bytes;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SUDHARSHAN NAVADA K
 */
public class PlantsInfo extends javax.swing.JFrame {

    /**
     * Creates new form PlantsInfo
     */
    public PlantsInfo() {
        initComponents();
    }
    byte[] photo=null ;
      private String filename=null;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pt1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pt2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        p7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        badd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 931));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1786, 931));
        jPanel1.setLayout(null);

        jl2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, null, java.awt.Color.pink, java.awt.Color.yellow));
        jPanel1.add(jl2);
        jl2.setBounds(675, 130, 356, 315);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Breed Name:");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 175, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Plant_Id      :");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(17, 238, 140, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Season         :");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(17, 301, 140, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Count           :");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(17, 364, 140, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("PlantName:");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(17, 424, 140, 30);

        p1.setBackground(new java.awt.Color(255, 255, 0));
        p1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jPanel1.add(p1);
        p1.setBounds(157, 177, 250, 30);

        p2.setBackground(new java.awt.Color(255, 255, 0));
        p2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel1.add(p2);
        p2.setBounds(157, 240, 250, 30);

        p3.setBackground(new java.awt.Color(255, 255, 0));
        p3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });
        jPanel1.add(p3);
        p3.setBounds(157, 303, 250, 30);

        p4.setBackground(new java.awt.Color(255, 255, 0));
        p4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(p4);
        p4.setBounds(157, 366, 250, 30);

        p5.setBackground(new java.awt.Color(255, 255, 0));
        p5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(p5);
        p5.setBounds(157, 426, 250, 30);

        pt1.setBackground(new java.awt.Color(255, 255, 0));
        pt1.setColumns(20);
        pt1.setRows(5);
        pt1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jScrollPane1.setViewportView(pt1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 2006, 1178, 0);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("MORE ABOUT PLANT::");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 528, 290, 45);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("ScientificName:");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(465, 541, 164, 30);

        p6.setBackground(new java.awt.Color(255, 255, 0));
        p6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });
        jPanel1.add(p6);
        p6.setBounds(647, 543, 250, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel11.setText("             GREEN HOUSE  NURSERY ");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 11, 1, new java.awt.Color(0, 20, 162)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 1180, 120);

        pt2.setBackground(new java.awt.Color(255, 255, 0));
        pt2.setColumns(20);
        pt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pt2.setRows(5);
        pt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(pt2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 580, 1100, 133);

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton4.setText("BACK");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.black, java.awt.Color.orange, java.awt.Color.black));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(219, 751, 170, 60);

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.black, java.awt.Color.orange, java.awt.Color.black));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(546, 751, 170, 60);

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton6.setText("ADD");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.black, java.awt.Color.orange, java.awt.Color.black));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(873, 751, 170, 60);

        p7.setBackground(new java.awt.Color(255, 255, 0));
        p7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7ActionPerformed(evt);
            }
        });
        jPanel1.add(p7);
        p7.setBounds(157, 480, 250, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("Price            :");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(12, 478, 140, 30);

        badd.setBackground(new java.awt.Color(153, 255, 0));
        badd.setText("ADD IMAGE");
        badd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.yellow, null, java.awt.Color.black));
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(933, 477, 185, 46);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nurseryy/k5fit.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 120, 1100, 810);

        jLabel2.setBackground(new java.awt.Color(102, 204, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nurseryy/admin.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(870, 0, 230, 100);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         AdminP p=new AdminP();
         p.setVisible(true); 
               this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        p1.setText(null); 
               p2.setText(null); 
               p3.setText(null); 
                p4.setText(null);
               p5.setText(null); 
               p6.setText(null); // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            
        String Bname=p1.getText();
        String id=p2.getText();
        String sea=p3.getText();
        String sci=p6.getText();
       // byte b[]=new byte[100];
        
      
       
        
       int count1=Integer.parseInt(p4.getText());
       String pname=p5.getText();
       int price=Integer.parseInt(p7.getText());
     //  b=jl2.getBytes();
       
       String info=pt2.getText();
       
        try{
                 Class.forName("com.mysql.jdbc.Driver");
                     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3308/nursery","root","");
                  java.sql.Statement st = c.createStatement();
                   String sql="INSERT INTO `plantinfo`(`Breed_name`, `Plant_id`, `Season`, `Count`, `Plant_Name`, `ScientificName`, `PriceP`, `Image`, `More`) VALUES ('"+Bname+"','"+id+"','"+sea+"','"+count1+"','"+pname+"','"+sci+"','"+price+"','"+photo+"','"+info+"')";
                  PreparedStatement ps = c.prepareStatement(sql);
                 
                  ps.executeUpdate();
                  

                 /* ResultSet r;
            r = s.executeQuery("insert into custinfo(Name,Phone)"+"values('"+s1"','"+ph"')");*/
            JOptionPane.showMessageDialog(null, "Plant info ADDED......");
            p1.setText(null);
            p2.setText(null);
            p3.setText(null);
            p4.setText(null);
            p5.setText(null);
            p6.setText(null);
            pt2.setText(null);
             p7.setText(null);
              jl2.setText(null);
            
        }
catch(Exception e){
    System.out.println(e);
    }// TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p7ActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
       
 JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
      
        filename = f.getAbsolutePath();
        ImageIcon imageicon =new ImageIcon( new ImageIcon(filename).getImage().getScaledInstance(jl2.getWidth(),jl2.getHeight(),Image.SCALE_DEFAULT));
          jl2.setIcon(imageicon);
        try
        {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new  ByteArrayOutputStream();
            // Class.forName("com.mysql.jdbc.Driver");
                    // Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3308/nursery","root","");
//                  java.sql.Statement st = c.createStatement();
//                   String sql="INSERT INTO `plantinfo(`Image`) VALUES (?)";
//                  PreparedStatement ps = c.prepareStatement(sql);
                 // ps.setBytes(1,photo);
                //  ps.executeUpdate();
                   
            
            byte[] buf = new byte[1024];
            for(int rNum;(rNum=fis.read(buf))!=-1;)
            {
                bos.write(buf,0,rNum);
            }
             photo = bos.toByteArray();  
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_baddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantsInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jl2;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextArea pt1;
    private javax.swing.JTextArea pt2;
    // End of variables declaration//GEN-END:variables
}
